### PR TITLE
correctly handle making a cert for a CNAME

### PR DESCRIPTION
**Pull request by jesopo**
to deduplicate picking which resolver we use, i've also refactored that out of `_has_dns_propagated`.

reference material: https://letsencrypt.org/2019/10/09/onboarding-your-customers-with-lets-encrypt-and-acme.html#the-advantages-of-a-cname

### CODE REVIEW

**Comment by YasharF** [comment]
I attempted to renew a cert with this change in place and got the following error.  Reverted the change back to the current code and it generated the cert without an issue.

```
 + CloudFlare hook executing: deploy_challenge
 + Domain [redacted] not found in any Cloudflare account
ERROR: deploy_challenge hook returned with non-zero exit code
 + CloudFlare hook executing: exit_hook
```

**Comment by YasharF** [comment]
What is the intended use case for this PR?  The current script supports getting a cert for a cname_subdomain as below.  The failed [redacted] domain that came up when I was testing, is actually the [some other domain] in the case below.

DNSSetting CNAME:  [cname_subdomain] -> [some other domain]

If you are trying to get certs for [some other domain], you should call the script on [some other domain] not [cname_subdomain], which should work out of the box.  Let me know if I am missing something.

**Comment by jesopo** [comment]
there is a good reason behind this PR, we rely on a private fork that does this over on libera.chat, but im away from my desk right now so I'll respond tomorrow

**Comment by YasharF** [comment]
Checking to see if you have any additional info.

**Pull request closed without merging**
